API_ENDPOINT: http://192.168.1.2:8109/v1/vision/detection
PROGRAM_INTERVAL: 1
PUMPPIN: 26
SPRAY_SPACING: 5
SPRAY_TIME: 1
TARGETS:
  - cat
CONFIDENCE_THRES: 0.5
MOTION_THRES: 0.2
CAMERA_UPDATE_INTERVAL: 10
